Upd flake  Disabled language formatter NVF.NIX
Fails to build

```text
       error: attribute 'prettier' missing
       at /nix/store/3vzc8fxjxvv0b0jrywian6ilb7bdk4y8-source/modules/plugins/languages/css.nix:45:17:
           44|     prettier = {
           45|       package = pkgs.prettier;
             |                 ^
           46|     };
       Did you mean prettierd?
```
`
 On branch stable-2.3
 Your branch is up to date with 'origin/stable-2.3'.

 Changes to be committed:
	modified:   CHANGELOG.md
	modified:   flake.lock
	modified:   modules/home/nvf.nix